version: '2'

services:
  proxy:
    build: ./
    volumes:
      - /mycroft_proxy/letsencrypt:/etc/letsencrypt
      - /mycroft_proxy/proxy/ssl:/etc/ssl/certs/nginx
    ports:
      - 80:80
      - 443:443
      - 8181:8181

