version: '2'

services:
  proxy:
    build: ./
    networks:
      - mycroft
    ports:
      - 80:80
      - 443:443
      - 8181:8181

networks:
  mycroft:
    external:
      name: mycroft_default
